/*
Given two sorted arrays A and B, generate all possible arrays such that first element is taken from A then from B then from A and so on in strictly increasing 
order till the arrays exhausted. The generated arrays should end with an element from B.

Input Format
The First Line contains Two Integer N and M, as the size of both the Arrays. 
Next Line contains N Integers separated by space as Array A[]. 
Next Line contains M Integers separated by space as Array B[].

Constraints
Arrays A[] and B[] are Sorted.

Output Format
Display the Sorted Arrays generated separated by a new Line.

Sample Input
3 4
10 15 25
1 5 20 30

Sample Output
10 20
10 20 25 30
10 30
15 20
15 20 25 30
15 30
25 30

Explanation
For the Given Sample output test case 10 20 can be generated by choosing 10 from the A[] and 20 from the B[].
*/

import java.util.*;
public class Main {
    public static void main(String[] args) {
		Scanner scn = new Scanner(System.in);
		int n = scn.nextInt();
		int m = scn.nextInt();
		int[] num1 = new int[n];
		int[] num2 = new int[m];
		for (int i = 0; i < n; i++)
			num1[i] = scn.nextInt();
		for (int j = 0; j < m; j++)
			num2[j] = scn.nextInt();
		genernum1te(num1, num2);
	}

	public static void genernum1teUtil(int num1[], int num2[], int arr[], int i, int j, int len, boolean flag) {
		if (flag) {
			if (len != 0)
				printnum1rr(arr, len + 1);
			for (int k = i; k < num1.length; k++) {
				if (len == 0) {
					arr[len] = num1[k];
					genernum1teUtil(num1, num2, arr, k + 1, j, len, !flag);
				} else if (num1[k] > arr[len]) {
					arr[len + 1] = num1[k];
					genernum1teUtil(num1, num2, arr, k + 1, j, len + 1, !flag);
				}
			}
		} else {
			for (int l = j; l < num2.length; l++) {
				if (num2[l] > arr[len]) {
					arr[len + 1] = num2[l];
					genernum1teUtil(num1, num2, arr, i, l + 1, len + 1, !flag);
				}
			}
		}
	}

	public static void genernum1te(int num1[], int num2[]) {
		int arr[] = new int[num1.length + num2.length];
		genernum1teUtil(num1, num2, arr, 0, 0, 0, true);
	}

	public static void printnum1rr(int arr[], int n) {
		for (int i = 0; i < n; i++)
			System.out.print(arr[i] + " ");
		System.out.println("");
	}
}
